apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-08-19T23:49:23Z
  generation: 1
  labels:
    run: champz-web-postgresdb
  name: champz-web-postgresdb
  namespace: default
  resourceVersion: "6876"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/champz-web-postgresdb
  uid: 7f9da832-a40a-11e8-9e59-025000000001
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: champz-web-postgresdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: champz-web-postgresdb
    spec:
      containers:
      - image: postgres:9.4.12-alpine
        imagePullPolicy: IfNotPresent
        name: champz-web-postgresdb
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-08-19T23:49:23Z
    lastUpdateTime: 2018-08-19T23:49:23Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-08-19T23:49:23Z
    lastUpdateTime: 2018-08-19T23:49:26Z
    message: ReplicaSet "champz-web-postgresdb-77f779d55c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
