apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-08-20T01:16:09Z
  generation: 1
  labels:
    run: champz-restservice-mongodb
  name: champz-restservice-mongodb
  namespace: default
  resourceVersion: "12897"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/champz-restservice-mongodb
  uid: 9e9845af-a416-11e8-9e59-025000000001
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: champz-restservice-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: champz-restservice-mongodb
    spec:
      containers:
      - image: corujito/champz-mongo:4.1.2
        imagePullPolicy: Never
        name: champz-restservice-mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: root_username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: root_password
          - name: MONGO_INITDB_DATABASE
            value: champz-prod-db
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: champz_username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: champz_password
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-08-20T01:16:09Z
    lastUpdateTime: 2018-08-20T01:16:09Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-08-20T01:16:09Z
    lastUpdateTime: 2018-08-20T01:16:09Z
    message: ReplicaSet "champz-restservice-mongodb-5549dcb88b" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
