apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  root_username: cm9vdA==
  root_password: cm9vdA==
  champz_username: Y2hhbXB6LXByb2Q=
  champz_password: cGFzc3dvcmQxMjM=
